version: "3"
services:
  minio_v3:
    container_name: minio_v3
    image: minio/minio
    ports:
      - "9010:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio1234
    volumes:
      - minio:/data
    restart: always
    platform: linux/x86_64
    command: server /data --console-address ":9001"
volumes:  
  minio:
